use_frameworks!

platform :ios, '9.0'

target 'AEAnimations_Example' do
  pod 'AEAnimations', :path => '../'

  target 'AEAnimations_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
